version: '3.8'
services: 
    redis: 
      image: redis:6
      ports:
        - "6379:6379" 
      
    
    db: 
      image: postgres:latest
      
      environment:
        - POSTGRES_USER=user 
        - POSTGRES_PASSWORD=password 
        - POSTGRES_DB=mydatabase 
      ports: 
        - "5432:5432"  
      volumes:
        - db_data:/var/lib/postgresql/data 
    
    web: 
      build: ./app
      ports: 
        - "5000:5000"  
      volumes: 
        - ./app:/app 
      depends_on:
        - db 
        - redis  
    nginx:
      image: nginx:latest
      ports:
      - "80:80"
      volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
      - web

volumes:
  db_data:


      
    
   
   
      

    



    